<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <RootNamespace>SystemTools.CrossPlatform</RootNamespace>
        <TargetName>SystemTools.CrossPlatform</TargetName>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <LangVersion>latest</LangVersion>
        <Configurations>Debug;Release;Debug_MSIX;Release_MSIX</Configurations>
        <EnableDynamicLoading>true</EnableDynamicLoading>
        <CreateCipx>true</CreateCipx>
        <OutputType>Library</OutputType>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="ClassIsland.PluginSdk" Version="2.1.1.1">
            <ExcludeAssets>runtime;native</ExcludeAssets>
        </PackageReference>

        <PackageReference Include="Avalonia" Version="12.1.1">
            <ExcludeAssets>runtime;native</ExcludeAssets>
        </PackageReference>
        <PackageReference Include="Avalonia.Desktop" Version="12.1.1">
            <ExcludeAssets>runtime;native</ExcludeAssets>
        </PackageReference>
        <PackageReference Include="Avalonia.Skia" Version="12.1.1">
            <ExcludeAssets>runtime;native</ExcludeAssets>
        </PackageReference>
        <PackageReference Include="CommunityToolkit.Mvvm" Version="8.2.1">
            <ExcludeAssets>runtime;native</ExcludeAssets>
        </PackageReference>
        <PackageReference Include="FluentAvaloniaUI" Version="3.0.0">
            <ExcludeAssets>runtime;native</ExcludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.10">
            <ExcludeAssets>runtime;native</ExcludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.10">
            <ExcludeAssets>runtime;native</ExcludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.10">
            <ExcludeAssets>runtime;native</ExcludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <None Update="manifest.yml">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="icon.png">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="title.png">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>

        <AvaloniaResource Include="Themes\CardTypeComponent\Theme.axaml.txt" />
        <AvaloniaResource Include="Themes\ClassWidgets\Theme.axaml.txt" />
        <AvaloniaResource Include="Themes\NotchStyle\Theme.axaml.txt" />
        <AvaloniaResource Include="Themes\ClassWidgets\上课.png" />
        <AvaloniaResource Include="Themes\ClassWidgets\课间休息.png" />
        <AvaloniaResource Include="Themes\ClassWidgets\无课程.png" />
        <AvaloniaResource Remove="cipx\**" />
        <None Remove="cipx\**" />
    </ItemGroup>

    <ItemGroup>
      <AvaloniaXaml Remove="cipx\**" />
    </ItemGroup>

    <ItemGroup>
      <Compile Remove="cipx\**" />
    </ItemGroup>

    <ItemGroup>
      <EmbeddedResource Remove="cipx\**" />
    </ItemGroup>

    <ItemGroup>
      <AdditionalFiles Remove="cipx\**" />
    </ItemGroup>

</Project>
